name: davidarteaga
favicon: null
layout_spectrum: 0.2494
typography_spectrum: 0.10376
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0a'
    - '#83acb0'
    - '#342a21'
    - '#818274'
    - '#4e473f'
  brandStrength: 0.75
  lightness: 0.4375
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
